version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: pontoeletronico-app
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
      - ./app/storage:/var/www/storage
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.4
    container_name: pontoeletronico-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pontoeletronico
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    command: --default-storage-engine=INNODB
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data: